import{a as w,S as v,i as l}from"./assets/vendor-DaWAOjWS.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&o(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const M="https://pixabay.com/api/",S="52982247-0d25e92a2d7c3074b601ee372",m=9;async function h(a,r=1){const e={key:S,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:m};return(await w.get(M,{params:e})).data}const g=m,i={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more-btn")},P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(a,r=!1){const e=a.map(o=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o.largeImageURL}">
          <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" loading="lazy"/>
        </a>
        <div class="info">
          <p class="info-item"><b>Likes:</b><p class="info-item-result">${o.likes}</p></p>
          <p class="info-item"><b>Views:</b><p class="info-item-result">${o.views}</p></p>
          <p class="info-item"><b>Comments:</b><p class="info-item-result">${o.comments}</p></p>
          <p class="info-item"><b>Downloads:</b><p class="info-item-result">${o.downloads}</p></p>
        </div>
      </li>`).join("");r?i.gallery.insertAdjacentHTML("beforeend",e):i.gallery.innerHTML=e,P.refresh()}function q(){i.gallery.innerHTML=""}function L(){i.loader.classList.remove("hidden")}function c(){i.loader.classList.add("hidden")}function E(){i.loadMoreBtn.classList.remove("is-hidden")}function b(){i.loadMoreBtn.classList.add("is-hidden")}const d={form:document.querySelector(".form"),input:document.querySelector('input[name="search-text"]'),loadMoreBtn:document.querySelector(".load-more-btn")};let f="",n=1,p=0;d.form.addEventListener("submit",R);d.loadMoreBtn.addEventListener("click",B);async function R(a){a.preventDefault();const r=d.input.value.trim();if(r===""){l.warning({title:"Warning",message:"Please enter a search query",position:"topRight"});return}q(),b(),L(),f=r,n=1;try{const e=await h(f,n);if(c(),!e.hits||e.hits.length===0){l.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p=e.totalHits,y(e.hits),d.input.value="";const o=Math.ceil(p/g);n<o&&E()}catch(e){c(),console.error(e),l.error({title:"Error",message:"Something went wrong while fetching images.",position:"topRight"})}}async function B(){n+=1,L();try{const a=await h(f,n);c(),y(a.hits,!0);const r=Math.ceil(p/g);n>=r&&(b(),l.info({title:"End of results",message:"You have reached the end of the search results.",position:"topRight"}));const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch(a){c(),console.error(a)}}
//# sourceMappingURL=index.js.map
